name: Terraform Plan

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Terraform Init
        run: terraform init

      - name: Run shell command
        run: |
          echo "The value of MY_SECRET is: ${{ secrets.__SECRET }}"
          # Use the secret in your shell command

      - name: Read env
        run: bash read_env.sh

      - name: Terraform Plan
        env:
            NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
            NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
            __SECURE_CREDENTIAL: ${{secrets.__SECURE_CREDENTIAL}}
            __SECRET: ${{secrets.__SECRET}}

        run: terraform plan
