name: Terraform Plan

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the secrets in a bash script
        run: |
          secrets=$(env | awk -F= '$1 ~ /^__\w+/ {print $1}')
          env | awk -F= '$1 ~ /^__\w+/ {print $1 "=" $2}' >> secrets.env
          bash read_env.sh secrets.env

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Read read_env.sh
        run: bash read_env.sh 

      - name: Terraform Plan
        env:
          NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
        run: terraform plan
