name: Terraform Plan

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ $changed_file == *"modules"* ]]; then
              folder_path=$(dirname "${changed_file}")
              echo "${folder_path}."
            fi
          done
      

      # - name: View the secrets context
      #   shell: bash
      #   run: |
      #     echo '${{ toJson(secrets) }}' > secrets.json
      #     [ -f read_env.sh ] && ./read_env.sh $(cat secrets.json) || true


      # - name: View the secrets context
      #   shell: bash
      #   run: |
      #     echo '${{ toJson(secrets) }}' > secrets.json
      #     if [ -f read_env.sh ]; then
      #       ./read_env.sh $(cat secrets.json)
      #     else
      #       echo "read_env.sh not found. Skipping execution."
      #     fi

      - name: View the secrets context
        shell: bash
        run: |
          echo '${{ toJson(secrets) }}' > secrets.json
          ./read_env.sh $(cat secrets.json)
      
                   
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Terraform Init
        run: terraform init

      - name: Read env
        run: bash read_env.sh

      - name: Terraform Plan
        env:
            NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
            NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
        run: terraform plan
