name: Terraform Plan

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the script with secrets
        run: ./read_secrets.sh secrets.json
      
      # - name: View the secrets context
      #   shell: bash
      #   run: |
      #     echo '${{ toJson(secrets) }}' > secrets.json
      #     ./read_env.sh $(cat secrets.json)
      
           
      # - name: View the secrets context
      #   shell: bash
      #   run: |
      #     echo "$SECRETS_CONTEXT" > secrets.json
      #     ./read_env.sh secrets.json
      #   env:
      #     SECRETS_CONTEXT: ${{ toJson(secrets) }}
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Terraform Init
        run: terraform init

      - name: Read env
        run: bash read_env.sh

      - name: Terraform Plan
        env:
            NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
            NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
        run: terraform plan
