name: Read GitHub Secrets

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  read_secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
          
      - name: Read Secrets
        run: |
          # Extract secrets starting with "__"
          secrets=$(env | grep -E '^__[[:alnum:]_]+=.*$' | cut -d= -f1)
          
          # Convert secrets to JSON object
          secrets_json=$(echo "$secrets" | awk '{printf("\"%s\":\"%s\",", $0, ENVIRON[$0])}' | sed 's/,$//')
          
          # Write secrets to read_env.sh
          echo "{ $secrets_json }" > read_env.sh
          
          # Display the contents of read_env.sh
          cat read_env.sh
          
      - name: Execute read_env.sh
        run: |
          # Make read_env.sh executable
          chmod +x read_env.sh
          
          # Execute read_env.sh
          ./read_env.sh
