name: Terraform Plan

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Terraform Init
        run: terraform init

      - name: Read env
        run: |
          for secret in ${{ secrets.* }}; do
            if [[ $secret =~ __[[:alnum:]] ]]; then
              echo "${{ secrets.$secret }}" >> secrets.txt
            fi
          done
          bash read_env.sh "$(cat secrets.txt)"

      - name: Terraform Plan
        env:
          NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
        run: terraform plan
