name: Terraform Plan

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
    #   - name: Use the secret in a bash script
    #     run: |
    #       bash read_env.sh "${{ secrets.__SECRET }}"

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Terraform Init
        run: terraform init

      - name: Read env
        run: |
          echo "Searching GitHub secrets"
          for secret_name in $(echo "${{ secrets }}" | jq -r 'to_entries[] | select(.key | startswith("__")) | .value'); do
            echo "${secret_name}" >> secrets.txt
          done
          bash read_env.sh "$(cat secrets.txt)"

      - name: Terraform Plan
        env:
          NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
        run: terraform plan
